---
- block:
  - name: Copy licenses to the licensemaster
    copy:
      src: "{{ item }}"
      dest: "{{ splunk_home}}/etc/license/enterprise/{{ item }}"
      owner: "{{ splunk_nix_user }}"
      group: "{{ splunk_nix_group }}"
      mode: 0644
    loop: "{{ splunk_licenses }}"
    notify: restart splunk
  when:
    - "'licensemaster' in group_names"
    - splunk_licenses != 'undefined'

- name: Set license master_uri
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: license
    option: master_uri
    value: "{{ splunk_uri_lm }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: 0644
  become: true
  notify: restart splunk
  when:
    - "'full' in group_names"
    - "'licensemaster' not in group_names"
    - splunk_uri_lm != 'undefined'
