---
- block:
  - name: Copy Licenses to Master
    copy:
      src: "{{ item }}"
      dest: "/tmp/{{ item }}"
    loop: "{{ splunk_licenses }}"
    
  - name: Install license on licensemaster
    command: "{{ splunk_home }}/bin/splunk add licenses /tmp/{{ item }} -auth {{ splunk_auth }}"
    become: true
    become_user: "{{ splunk_nix_user }}"
    loop: "{{ splunk_licenses }}"
    ignore_errors: yes
    register: license_result
    changed_when: '"The licenses object has been added" in license_result.stdout'
    notify: restart splunk

  - name: Clean Up licenses
    file:
      path: "/tmp/{{ item }}"
      state: absent
    become: true
    loop: "{{ splunk_licenses }}"

  when:
    - "'licensemaster' in group_names"
    - splunk_licenses is defined
    - splunk_licenses != 'undefined'

- name: Set license master_uri
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: license
    option: master_uri
    value: "{{ splunk_uri_lm }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: 0644
  become: true
  notify: restart splunk
  when:
    - "'full' in group_names"
    - "'licensemaster' not in group_names"
    - splunk_uri_lm != 'undefined'
